### ISSUE TITLE
File operations are not atomic

### ISSUE THREAD

**Issue by oschwald** [tronovav/geoip2-update#2]
Currently, the script deletes the directory and then extracts the new directory. If this was done while the application was running, it could lead to errors in the window of time between the deletion and when the files are fully extracted.

The official `geoipupdate` client avoids this issue by atomically replacing the file. It does this by extracting the new file to a temp file on the file system and then moving the new file over the old file. On unix systems, a move of a file on the file system is an atomic operation.

This is complicated a bit by the fact that this library is operating on directories rather than individual files as you cannot move a directory over another directory. If the library only handled MMDB files, I would recommend just operating on those individual files. However, the CSV files present a somewhat more difficult case as you want to replace them all at once. This could be accomplished by using a symlink to the actual directory and atomically replacing that.

[This article](https://axialcorps.wordpress.com/2013/07/03/atomically-replacing-files-and-directories/) covers this at a bit more depth. I only glanced at it, but the information seems correct.

**Comment by tronovav** [comment]
In version 2.1.0, we implemented the atomicity of the update, but with some comments.

Currently, the atomicity of the update operation is implemented at the level of individual database files.

The structure of the mmdb and csv databases is different. Mmdb databases consist of a single database file. Thus, when updating databases mmdb, the operation is completely atomic and the possibility that when updating databases, there will be errors associated with the short-term absence of the mmdb file. Since the files are atomically replaced with new ones.

CSV databases consist of multiple files. When updating csv database revisions, each csv file is also replaced atomically, and the chance of a file missing during the update is eliminated. However, when updating the csv databases while the application is running, there is a chance that within a minimum amount of time, one csv file is already new and the other will still have an old version.
