### ISSUE TITLE
Licence key in composer hinders pushing to public repository

### ISSUE THREAD

**Issue by lmeyer1** [tronovav/geoip2-update#4]
The licence key is required in the `composer.json`. This is not so good, because I cannot push this file to my public repository then.

Do you have a recommended work-around?

**Comment by tronovav** [comment]
Of course, the license key should not be push to the public repository.

If you want to add our library to the dependency, then you can do it, but do not fill in the `post-update-cmd` and `extra` sections in your `composer.json`. Then your project will work but simply without updating the `geoip2` databases.
And in order for your users to know about the possibility of automatic updating of `geoip2` databases, you need to write about this feature in your `README.md` file and your users will be able to add all the necessary settings with their own license key. Or write about this feature and give a link to our documentation.

At the moment it is done like this. But the question is interesting and we will think about it in order to add some more possibility.

**Comment by lmeyer1** [comment]
Update via a php script and a cron is thus the only viable solution.

**Comment by tronovav** [comment]
In the v2.1.16 release, we added the ability to store the license key and other settings outside the project. Since it is made by Maxmind. You can create a config file and store it outside of public repositories. Users of your programs can generate it themselves. See updated documentation for our project.

**Comment by lmeyer1** [comment]
@tronovav Thank you very much for this great improvement. Now I can set up a more automated update. Great!
